### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/CatSceneEditor#1]
i have no problem with earlier build, but this time it gave me error...
used version, visual studio 2017 enterprise
<a href="https://imgur.com/2V7nXwO"><img src="https://i.imgur.com/2V7nXwO.png" title="source: imgur.com" /></a>

**Comment by marcussacana** [comment]
try now

**Comment by 0xh3LL0** [comment]
i'll try it and update later

**Comment by 0xh3LL0** [comment]
build success!
thanks!
