### ISSUE TITLE
When I try to translate it into Chinese, it shows「???」.

### ISSUE THREAD

**Issue by Shinya-Shimokawa** [marcussacana/CatSceneEditor#2]
![捕获](https://user-images.githubusercontent.com/45751534/55291651-7bd24380-5413-11e9-9ac4-dd46807ac110.PNG)

Is that an encoding problem? How to correct it？

**Comment by trigger-segfault** [comment]
I have very little knowledge about CJK languages other than the basics through working with CatSystem2, but are the characters that you're losing present in the Shift JIS (codepage 932) encoding?

If you post the actual characters that are causing problems I can try encoding them myself to see the outcome.

**Comment by marcussacana** [comment]
Well, upload this script to we take a look to.

**Comment by marcussacana** [comment]
Yeah, the .cst use the SJIS, If i'm not wrong the chinese use the 936...
If you want put chineses text in the 932 scripts, basically you can't do easy.
There is some exits to you, if this is your problem.

1. Translate using the CSTL, it's a new type of files (for now i only found in the nekopara vol.3) that uses the UTF-8 encoding and I think don't will cause any trouble to you, the problem is I never tried put the cstl script in older games.
2. Create by your self a font that replace japanese useless characters with your chinese characters.
3. Modify the engine to use the 936 encoding, and you can change my tool encoding easy here:  
https://github.com/marcussacana/CatSceneEditor/blob/39e996da14cc94f68aaee1cafc6862e6035d7180/CatSceneEditor/Main.cs#L20  
Modify the engine is the 'proper way' to do this, but it's very complex.

To change the catsystem2 font it's very easy, just edit that xml file in the game directory.

**Comment by trigger-segfault** [comment]
I've actually not had any success with changing the game fonts through `startup.xml`. The Grisaia games explicitly have launcher executables *just* to fix this by updating the font in `setup.xml` during the second launch.

**Comment by marcussacana** [comment]
When the game starts for the first time, he create a copy of the .xml in the save directory, then if you try change the font in the .xml of the game directory, the game will just ignore reading the .xml in the save directory.

But when i'm with trouble to change the game font, I use my StringReloads: https://github.com/marcussacana/StringReloads
You can inject in the game with few commands if you use this one: https://github.com/marcussacana/RemoteControl

After you inject the SRL you just need setup in the SRL.ini to change the font (Enable the CreateFont and CreateFontIndirect and change that "Gothic Modded" to what you want.

Well, using the remotecontrol to inject the SRL makes your patch require a 'launcher' to inject everytime, to prevent this, only if you edit the executable.

If you are with lazy, I have this tool that I made for tests and never published, just edit the .ini to work with your game.
[FontHook.rar](https://github.com/marcussacana/CatSceneEditor/files/3027387/FontHook.zip)

**Comment by trigger-segfault** [comment]
Damn, your GitHub has every base covered. I'll definitely check it out!

**Comment by Shinya-Shimokawa** [comment]
> Yeah, the .cst use the SJIS, If i'm not wrong the chinese use the 936...
> If you want put chineses text in the 932 scripts, basically you can't do easy.
> There is some exits to you, if this is your problem.
> 
> 1. Translate using the CSTL, it's a new type of files (for now i only found in the nekopara vol.3) that uses the UTF-8 encoding and I think don't will cause any trouble to you, the problem is I never tried put the cstl script in older games.
> 2. Create by your self a font that replace japanese useless characters with your chinese characters.
> 3. Modify the engine to use the 936 encoding, and you can change my tool encoding easy here:
>    
>      
>        
>          [CatSceneEditor/CatSceneEditor/Main.cs](https://github.com/marcussacana/CatSceneEditor/blob/39e996da14cc94f68aaee1cafc6862e6035d7180/CatSceneEditor/Main.cs#L20)
>        
>        
>             Line 20
>          in
>          [39e996d](/marcussacana/CatSceneEditor/commit/39e996da14cc94f68aaee1cafc6862e6035d7180)
>        
>        
>        
>        
>    
>            
>              
>               public Encoding Encoding = Encoding.GetEncoding(932); 
>            
>        
>      
>    
>    
>    Modify the engine is the 'proper way' to do this, but it's very complex.
> 
> To change the catsystem2 font it's very easy, just edit that xml file in the game directory.

It seems that these three ways all need an exe change...I'll have a try, thanks.

**Comment by 0xD3ADCODE** [comment]
> When the game starts for the first time, he create a copy of the .xml in the save directory, then if you try change the font in the .xml of the game directory, the game will just ignore reading the .xml in the save directory.
> 
> But when i'm with trouble to change the game font, I use my StringReloads: https://github.com/marcussacana/StringReloads You can inject in the game with few commands if you use this one: https://github.com/marcussacana/RemoteControl
> 
> After you inject the SRL you just need setup in the SRL.ini to change the font (Enable the CreateFont and CreateFontIndirect and change that "Gothic Modded" to what you want.
> 
> Well, using the remotecontrol to inject the SRL makes your patch require a 'launcher' to inject everytime, to prevent this, only if you edit the executable.
> 
> If you are with lazy, I have this tool that I made for tests and never published, just edit the .ini to work with your game. [FontHook.rar](https://github.com/marcussacana/CatSceneEditor/files/3027387/FontHook.zip)

Hi, [marcussacana](https://github.com/marcussacana)! Thank you for **FontHook** app! It's really handy with AdvHD engine and others.

Can you, please, clarify license for source code inside archive or grant/deny permission for modifying and uploading new version to my GitHub account? I want implement some modification to suit my cases and provide them to other people

**Comment by marcussacana** [comment]
You can modify any of my tools as you wish, there is no license just because I really don't mind about that usually, instead, when I put a license is because I care about the tool.

Also, nowdays I would recommend to give a look to StringReloads, it was a lot of features and more advanced font hooking.

**Comment by 0xD3ADCODE** [comment]
> You can modify any of my tools as you wish, there is no license just because I really don't mind about that usually, instead, when I put a license is because I care about the tool.
> 
> Also, nowdays I would recommend to give a look to StringReloads, it was a lot of features and more advanced font hooking.

Cool, thanks a lot!
StringReloads is cool tool but at some point... complicated for me. I just need font "swapping" feature to run some VNa with Cyrillic letters on Steam Deck, so, FontHook is perfect
