### ISSUE TITLE
[ShinKoihime Musou :Ryuuki no Taimou] Extract script into .txt and compile more easily

### ISSUE THREAD

**Issue by tbhoang12** [marcussacana/CatSceneEditor#3]
hi,can you make your tool extract the script .cst files into .txt file and then repack back more easily ?
Because when i'm trying to translate with your tool default editor ,it's so tiny and inconvenient .If I can edit the script with .txt file using Notepad++ or something it would be better o/
![ShinKoihime Premium6_22_2021 , 5_56_41 PM](https://user-images.githubusercontent.com/76590480/123481028-61589600-d62d-11eb-8237-aa149a1f189d.png)

The game i'm trying to TL [(https://vndb.org/r71356)]
When i'm hooking the game to read with Textractor , it said the game engine is Catsystem3 not CS2 ,so if you can please update your tool
[SKMK files here in case you want to test](https://www.ryuugames.com/shin-koihime-†-musou-premium-package-shoku-free-download-googledrive/)

P/s: If you can re design your tool UI to become more user-friendly and not just a bunch CMD windows commands it would be great ,because translators like me don't have any tech skill what so ever ,thanks in advance o/

**Comment by marcussacana** [comment]
Done years ago in the SacanaWrapper.

**Comment by tbhoang12** [comment]
when I extract update01.int using Garbro tool, it gave me a .fes file and one BindingData.khe (which I know contains images files for UI in-game)

But I can't find any tool online that can extract this BindingData.khe file into .hg3 image files of Catsystem2. Do you know how to ?
![Binding Data SKM new6_22_2021 , 5_58_54 PM](https://user-images.githubusercontent.com/76590480/123495823-7cd49880-d64f-11eb-8ae2-a677d29a5104.png)

**Comment by marcussacana** [comment]
I Never saw this format before
